### PR TITLE
Fix Issue Schema for missing description field

### PR DESCRIPTION
**Pull request by bpepple**
Title pretty much says it all.

### CODE REVIEW

**Comment by Buried-In-Code** [comment]
Does this affect Issue as well? or is this limited to just IssueList?

**Comment by bpepple** [comment]
> Does this affect Issue as well? or is this limited to just IssueList?

Haven't ran across this bug in the Issue schema, just the IssueList schema.

**Comment by Buried-In-Code** [comment]
Using the Issue ID `18006` (the same as the one you used for IssueList), it looks like it Issue.description also needs to become allow_none

**Comment by Buried-In-Code** [comment]
This has been fixed as part of #99

**Pull request closed without merging**
