### PR TITLE
Format-dates

### PR DESCRIPTION
**Pull request by bpepple**
- Fix date formatting for creator date of death
- Use Meta class to handle primary date formats

### CODE REVIEW

**Comment by Buried-In-Code** [comment]
While we're updating the dates I think it'd also be good to change the DoB and DoD to be `Date` format instead of `Datetime`.

**Comment by Buried-In-Code** [comment]
Also the tests should pass if you include the Github Secret `COMICVINE_API_KEY` to your fork config.

**Comment by bpepple** [comment]
> Also the tests should pass if you include the Github Secret `COMICVINE_API_KEY` to your fork config.

Thought I'd set it, but I'll check it again on my fork.

**Comment by bpepple** [comment]
> While we're updating the dates I think it'd also be good to change the DoB and DoD to be `Date` format instead of `Datetime`.

Not a bad idea.  Give me a minute and I'll push a new commit to change that.

**Comment by bpepple** [comment]
Looks like my GH Secret Key is still not working. Really, I think an expiring testing cache/env secrets isn't that great of a solution for testing, since it sort of defeats the purpose of having a testing cache if it's just going to expire every 14 days.

Beyond the whole everyone who forks it needing to setup a GH secret hassle, you run into the potential problem with the data from ComicVine possibly changing due to editing.  I'd lean towards either using a non-expiring testing cache, or uses fixtures for the data.

**Comment by Buried-In-Code** [comment]
That's true, I guess my implementation doesn't work for tests as I'd planned. I'll take a look at my implementation in another PR and make it possible to not expire the cache for tests

**Pull request merged**
